# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Matt Bell
email: matt@mbell.me
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

paginate: 5
paginate_path: "/blog/page/:num/"

collections:
  projects:
    output: true
    permalink: /projects/:path/
  redirects:
    output: true
    permalink: /:path/
  stickers:
    output: true
    permalink: /:collection/:path/
  posts:
    output: true
    permalink: /blog/:path/

# Build settings
markdown: kramdown
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
theme: minima
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate
  - jemoji
  - rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - files/*.tex
  - node_modules

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      lauout: post
      is_post: true
  - scope:
      path: ""
      type: stickers
    values:
      layout: sticker
